version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    volumes:
      - minio_data:/data

  ingest-service:
    build:
      context: .
      dockerfile: ./ingest/Dockerfile
    depends_on:
      - qdrant
      - minio
    ports:
      - "8000:8000"
    environment:
      - AWS_S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL
      - QDRANT_URL

  rag-service:
    build:
      context: .
      dockerfile: ./rag/Dockerfile
    depends_on:
      - qdrant
      - minio
    ports:
      - "8001:8000"
    environment:
      - AWS_S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL
      - QDRANT_URL
      - YANDEX_API_TOKEN
      - YANDEX_API_URL

volumes:
  qdrant_data:
  minio_data:
