graph LR

m_src_requests_sessions_py["src/requests/sessions.py"]
m_src_requests_adapters_py["src/requests/adapters.py"]
m_src_requests_api_py["src/requests/api.py"]
m_src_requests_models_py["src/requests/models.py"]
m_src_requests_utils_py["src/requests/utils.py"]
m_src_requests_auth_py["src/requests/auth.py"]
m_src_requests_compat_py["src/requests/compat.py"]
m_src_requests_hooks_py["src/requests/hooks.py"]
m_src_requests_packages_py["src/requests/packages.py"]
m_src_requests_status_codes_py["src/requests/status_codes.py"]
m_src_requests_certs_py["src/requests/certs.py"]
m_src_requests_help_py["src/requests/help.py"]
m_src_requests_cookies_py["src/requests/cookies.py"]
m_src_requests_structures_py["src/requests/structures.py"]
m_src_requests_exceptions_py["src/requests/exceptions.py"]
m_src_requests___init___py["src/requests/__init__.py"]
m_src_requests___version___py["src/requests/__version__.py"]
m_src_requests__internal_utils_py["src/requests/_internal_utils.py"]
pkg_sessions_py["sessions.py"]
 --> pkg_sessions_py
pkg_adapters_py["adapters.py"]
 --> pkg_adapters_py
pkg_api_py["api.py"]
 --> pkg_api_py
pkg_models_py["models.py"]
 --> pkg_models_py
pkg_utils_py["utils.py"]
 --> pkg_utils_py
pkg_auth_py["auth.py"]
 --> pkg_auth_py
pkg_compat_py["compat.py"]
 --> pkg_compat_py
pkg_hooks_py["hooks.py"]
 --> pkg_hooks_py
pkg_packages_py["packages.py"]
 --> pkg_packages_py
pkg_status_codes_py["status_codes.py"]
 --> pkg_status_codes_py
pkg_certs_py["certs.py"]
 --> pkg_certs_py
pkg_help_py["help.py"]
 --> pkg_help_py
pkg_cookies_py["cookies.py"]
 --> pkg_cookies_py
pkg_structures_py["structures.py"]
 --> pkg_structures_py
pkg_exceptions_py["exceptions.py"]
 --> pkg_exceptions_py
pkg___init___py["__init__.py"]
 --> pkg___init___py
pkg___version___py["__version__.py"]
 --> pkg___version___py
pkg__internal_utils_py["_internal_utils.py"]
 --> pkg__internal_utils_py
f_src_requests_sessions_py_merge_setting["merge_setting"]
m_src_requests_sessions_py --> f_src_requests_sessions_py_merge_setting
f_src_requests_sessions_py_merge_hooks["merge_hooks"]
m_src_requests_sessions_py --> f_src_requests_sessions_py_merge_hooks
c_src_requests_sessions_py_SessionRedirectMixin["SessionRedirectMixin"]
m_src_requests_sessions_py --> c_src_requests_sessions_py_SessionRedirectMixin
c_src_requests_sessions_py_Session["Session"]
m_src_requests_sessions_py --> c_src_requests_sessions_py_Session
f_src_requests_sessions_py_session["session"]
m_src_requests_sessions_py --> f_src_requests_sessions_py_session
f_src_requests_sessions_py_prepare_request["f:src/requests/sessions.py:prepare_request"]
 --> f_src_requests_sessions_py_prepare_request
f_src_requests_sessions_py_merge_environment_settings["f:src/requests/sessions.py:merge_environment_settings"]
 --> f_src_requests_sessions_py_merge_environment_settings
c_src_requests_adapters_py_BaseAdapter["BaseAdapter"]
m_src_requests_adapters_py --> c_src_requests_adapters_py_BaseAdapter
c_src_requests_adapters_py_HTTPAdapter["HTTPAdapter"]
m_src_requests_adapters_py --> c_src_requests_adapters_py_HTTPAdapter
f_src_requests_api_py_request["request"]
m_src_requests_api_py --> f_src_requests_api_py_request
f_src_requests_api_py_get["get"]
m_src_requests_api_py --> f_src_requests_api_py_get
f_src_requests_api_py_options["options"]
m_src_requests_api_py --> f_src_requests_api_py_options
f_src_requests_api_py_head["head"]
m_src_requests_api_py --> f_src_requests_api_py_head
f_src_requests_api_py_post["post"]
m_src_requests_api_py --> f_src_requests_api_py_post
f_src_requests_api_py_put["put"]
m_src_requests_api_py --> f_src_requests_api_py_put
f_src_requests_api_py_patch["patch"]
m_src_requests_api_py --> f_src_requests_api_py_patch
f_src_requests_api_py_delete["delete"]
m_src_requests_api_py --> f_src_requests_api_py_delete
c_src_requests_models_py_RequestEncodingMixin["RequestEncodingMixin"]
m_src_requests_models_py --> c_src_requests_models_py_RequestEncodingMixin
c_src_requests_models_py_RequestHooksMixin["RequestHooksMixin"]
m_src_requests_models_py --> c_src_requests_models_py_RequestHooksMixin
c_src_requests_models_py_Request["Request"]
m_src_requests_models_py --> c_src_requests_models_py_Request
c_src_requests_models_py_PreparedRequest["PreparedRequest"]
m_src_requests_models_py --> c_src_requests_models_py_PreparedRequest
c_src_requests_models_py_Response["Response"]
m_src_requests_models_py --> c_src_requests_models_py_Response
f_src_requests_utils_py_dict_to_sequence["dict_to_sequence"]
m_src_requests_utils_py --> f_src_requests_utils_py_dict_to_sequence
f_src_requests_utils_py_super_len["super_len"]
m_src_requests_utils_py --> f_src_requests_utils_py_super_len
f_src_requests_utils_py_get_netrc_auth["get_netrc_auth"]
m_src_requests_utils_py --> f_src_requests_utils_py_get_netrc_auth
f_src_requests_utils_py_guess_filename["guess_filename"]
m_src_requests_utils_py --> f_src_requests_utils_py_guess_filename
f_src_requests_utils_py_extract_zipped_paths["extract_zipped_paths"]
m_src_requests_utils_py --> f_src_requests_utils_py_extract_zipped_paths
f_src_requests_utils_py_atomic_open["atomic_open"]
m_src_requests_utils_py --> f_src_requests_utils_py_atomic_open
f_src_requests_utils_py_from_key_val_list["from_key_val_list"]
m_src_requests_utils_py --> f_src_requests_utils_py_from_key_val_list
f_src_requests_utils_py_to_key_val_list["to_key_val_list"]
m_src_requests_utils_py --> f_src_requests_utils_py_to_key_val_list
f_src_requests_utils_py_parse_list_header["parse_list_header"]
m_src_requests_utils_py --> f_src_requests_utils_py_parse_list_header
f_src_requests_utils_py_parse_dict_header["parse_dict_header"]
m_src_requests_utils_py --> f_src_requests_utils_py_parse_dict_header
f_src_requests_utils_py_unquote_header_value["unquote_header_value"]
m_src_requests_utils_py --> f_src_requests_utils_py_unquote_header_value
f_src_requests_utils_py_dict_from_cookiejar["dict_from_cookiejar"]
m_src_requests_utils_py --> f_src_requests_utils_py_dict_from_cookiejar
f_src_requests_utils_py_add_dict_to_cookiejar["add_dict_to_cookiejar"]
m_src_requests_utils_py --> f_src_requests_utils_py_add_dict_to_cookiejar
f_src_requests_utils_py_get_encodings_from_content["get_encodings_from_content"]
m_src_requests_utils_py --> f_src_requests_utils_py_get_encodings_from_content
f_src_requests_utils_py_get_encoding_from_headers["get_encoding_from_headers"]
m_src_requests_utils_py --> f_src_requests_utils_py_get_encoding_from_headers
f_src_requests_utils_py_stream_decode_response_unicode["stream_decode_response_unicode"]
m_src_requests_utils_py --> f_src_requests_utils_py_stream_decode_response_unicode
f_src_requests_utils_py_iter_slices["iter_slices"]
m_src_requests_utils_py --> f_src_requests_utils_py_iter_slices
f_src_requests_utils_py_get_unicode_from_response["get_unicode_from_response"]
m_src_requests_utils_py --> f_src_requests_utils_py_get_unicode_from_response
f_src_requests_utils_py_unquote_unreserved["unquote_unreserved"]
m_src_requests_utils_py --> f_src_requests_utils_py_unquote_unreserved
f_src_requests_utils_py_requote_uri["requote_uri"]
m_src_requests_utils_py --> f_src_requests_utils_py_requote_uri
f_src_requests_utils_py_address_in_network["address_in_network"]
m_src_requests_utils_py --> f_src_requests_utils_py_address_in_network
f_src_requests_utils_py_dotted_netmask["dotted_netmask"]
m_src_requests_utils_py --> f_src_requests_utils_py_dotted_netmask
f_src_requests_utils_py_is_ipv4_address["is_ipv4_address"]
m_src_requests_utils_py --> f_src_requests_utils_py_is_ipv4_address
f_src_requests_utils_py_is_valid_cidr["is_valid_cidr"]
m_src_requests_utils_py --> f_src_requests_utils_py_is_valid_cidr
f_src_requests_utils_py_set_environ["set_environ"]
m_src_requests_utils_py --> f_src_requests_utils_py_set_environ
f_src_requests_utils_py_should_bypass_proxies["should_bypass_proxies"]
m_src_requests_utils_py --> f_src_requests_utils_py_should_bypass_proxies
f_src_requests_utils_py_get_environ_proxies["get_environ_proxies"]
m_src_requests_utils_py --> f_src_requests_utils_py_get_environ_proxies
f_src_requests_utils_py_select_proxy["select_proxy"]
m_src_requests_utils_py --> f_src_requests_utils_py_select_proxy
f_src_requests_utils_py_resolve_proxies["resolve_proxies"]
m_src_requests_utils_py --> f_src_requests_utils_py_resolve_proxies
f_src_requests_utils_py_default_user_agent["default_user_agent"]
m_src_requests_utils_py --> f_src_requests_utils_py_default_user_agent
f_src_requests_utils_py_default_headers["default_headers"]
m_src_requests_utils_py --> f_src_requests_utils_py_default_headers
f_src_requests_utils_py_parse_header_links["parse_header_links"]
m_src_requests_utils_py --> f_src_requests_utils_py_parse_header_links
f_src_requests_utils_py_guess_json_utf["guess_json_utf"]
m_src_requests_utils_py --> f_src_requests_utils_py_guess_json_utf
f_src_requests_utils_py_prepend_scheme_if_needed["prepend_scheme_if_needed"]
m_src_requests_utils_py --> f_src_requests_utils_py_prepend_scheme_if_needed
f_src_requests_utils_py_get_auth_from_url["get_auth_from_url"]
m_src_requests_utils_py --> f_src_requests_utils_py_get_auth_from_url
f_src_requests_utils_py_check_header_validity["check_header_validity"]
m_src_requests_utils_py --> f_src_requests_utils_py_check_header_validity
f_src_requests_utils_py_urldefragauth["urldefragauth"]
m_src_requests_utils_py --> f_src_requests_utils_py_urldefragauth
f_src_requests_utils_py_rewind_body["rewind_body"]
m_src_requests_utils_py --> f_src_requests_utils_py_rewind_body
c_src_requests_auth_py_AuthBase["AuthBase"]
m_src_requests_auth_py --> c_src_requests_auth_py_AuthBase
c_src_requests_auth_py_HTTPBasicAuth["HTTPBasicAuth"]
m_src_requests_auth_py --> c_src_requests_auth_py_HTTPBasicAuth
c_src_requests_auth_py_HTTPProxyAuth["HTTPProxyAuth"]
m_src_requests_auth_py --> c_src_requests_auth_py_HTTPProxyAuth
c_src_requests_auth_py_HTTPDigestAuth["HTTPDigestAuth"]
m_src_requests_auth_py --> c_src_requests_auth_py_HTTPDigestAuth
f_src_requests_hooks_py_default_hooks["default_hooks"]
m_src_requests_hooks_py --> f_src_requests_hooks_py_default_hooks
f_src_requests_hooks_py_dispatch_hook["dispatch_hook"]
m_src_requests_hooks_py --> f_src_requests_hooks_py_dispatch_hook
f_src_requests_help_py_info["info"]
m_src_requests_help_py --> f_src_requests_help_py_info
f_src_requests_help_py_main["main"]
m_src_requests_help_py --> f_src_requests_help_py_main
c_src_requests_cookies_py_MockRequest["MockRequest"]
m_src_requests_cookies_py --> c_src_requests_cookies_py_MockRequest
c_src_requests_cookies_py_MockResponse["MockResponse"]
m_src_requests_cookies_py --> c_src_requests_cookies_py_MockResponse
f_src_requests_cookies_py_extract_cookies_to_jar["extract_cookies_to_jar"]
m_src_requests_cookies_py --> f_src_requests_cookies_py_extract_cookies_to_jar
f_src_requests_cookies_py_get_cookie_header["get_cookie_header"]
m_src_requests_cookies_py --> f_src_requests_cookies_py_get_cookie_header
f_src_requests_cookies_py_remove_cookie_by_name["remove_cookie_by_name"]
m_src_requests_cookies_py --> f_src_requests_cookies_py_remove_cookie_by_name
c_src_requests_cookies_py_CookieConflictError["CookieConflictError"]
m_src_requests_cookies_py --> c_src_requests_cookies_py_CookieConflictError
c_src_requests_cookies_py_RequestsCookieJar["RequestsCookieJar"]
m_src_requests_cookies_py --> c_src_requests_cookies_py_RequestsCookieJar
f_src_requests_cookies_py_create_cookie["create_cookie"]
m_src_requests_cookies_py --> f_src_requests_cookies_py_create_cookie
f_src_requests_cookies_py_morsel_to_cookie["morsel_to_cookie"]
m_src_requests_cookies_py --> f_src_requests_cookies_py_morsel_to_cookie
f_src_requests_cookies_py_cookiejar_from_dict["cookiejar_from_dict"]
m_src_requests_cookies_py --> f_src_requests_cookies_py_cookiejar_from_dict
f_src_requests_cookies_py_merge_cookies["merge_cookies"]
m_src_requests_cookies_py --> f_src_requests_cookies_py_merge_cookies
f_src_requests_cookies_py_set["f:src/requests/cookies.py:set"]
 --> f_src_requests_cookies_py_set
f_src_requests_cookies_py___delitem__["f:src/requests/cookies.py:__delitem__"]
 --> f_src_requests_cookies_py___delitem__
c_src_requests_structures_py_CaseInsensitiveDict["CaseInsensitiveDict"]
m_src_requests_structures_py --> c_src_requests_structures_py_CaseInsensitiveDict
c_src_requests_structures_py_LookupDict["LookupDict"]
m_src_requests_structures_py --> c_src_requests_structures_py_LookupDict
c_src_requests_exceptions_py_RequestException["RequestException"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_RequestException
c_src_requests_exceptions_py_InvalidJSONError["InvalidJSONError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_InvalidJSONError
c_src_requests_exceptions_py_JSONDecodeError["JSONDecodeError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_JSONDecodeError
c_src_requests_exceptions_py_HTTPError["HTTPError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_HTTPError
c_src_requests_exceptions_py_ConnectionError["ConnectionError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_ConnectionError
c_src_requests_exceptions_py_ProxyError["ProxyError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_ProxyError
c_src_requests_exceptions_py_SSLError["SSLError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_SSLError
c_src_requests_exceptions_py_Timeout["Timeout"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_Timeout
c_src_requests_exceptions_py_ConnectTimeout["ConnectTimeout"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_ConnectTimeout
c_src_requests_exceptions_py_ReadTimeout["ReadTimeout"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_ReadTimeout
c_src_requests_exceptions_py_URLRequired["URLRequired"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_URLRequired
c_src_requests_exceptions_py_TooManyRedirects["TooManyRedirects"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_TooManyRedirects
c_src_requests_exceptions_py_MissingSchema["MissingSchema"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_MissingSchema
c_src_requests_exceptions_py_InvalidSchema["InvalidSchema"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_InvalidSchema
c_src_requests_exceptions_py_InvalidURL["InvalidURL"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_InvalidURL
c_src_requests_exceptions_py_InvalidHeader["InvalidHeader"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_InvalidHeader
c_src_requests_exceptions_py_InvalidProxyURL["InvalidProxyURL"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_InvalidProxyURL
c_src_requests_exceptions_py_ChunkedEncodingError["ChunkedEncodingError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_ChunkedEncodingError
c_src_requests_exceptions_py_ContentDecodingError["ContentDecodingError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_ContentDecodingError
c_src_requests_exceptions_py_StreamConsumedError["StreamConsumedError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_StreamConsumedError
c_src_requests_exceptions_py_RetryError["RetryError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_RetryError
c_src_requests_exceptions_py_UnrewindableBodyError["UnrewindableBodyError"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_UnrewindableBodyError
c_src_requests_exceptions_py_RequestsWarning["RequestsWarning"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_RequestsWarning
c_src_requests_exceptions_py_FileModeWarning["FileModeWarning"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_FileModeWarning
c_src_requests_exceptions_py_RequestsDependencyWarning["RequestsDependencyWarning"]
m_src_requests_exceptions_py --> c_src_requests_exceptions_py_RequestsDependencyWarning
f_src_requests___init___py_check_compatibility["check_compatibility"]
m_src_requests___init___py --> f_src_requests___init___py_check_compatibility
f_src_requests__internal_utils_py_to_native_string["to_native_string"]
m_src_requests__internal_utils_py --> f_src_requests__internal_utils_py_to_native_string
f_src_requests__internal_utils_py_unicode_is_ascii["unicode_is_ascii"]
m_src_requests__internal_utils_py --> f_src_requests__internal_utils_py_unicode_is_ascii
f_src_requests_sessions_py_merge_hooks -->|вызывает| f_src_requests_sessions_py_merge_setting
f_src_requests_sessions_py_prepare_request -->|вызывает| f_src_requests_sessions_py_merge_setting
f_src_requests_sessions_py_prepare_request -->|вызывает| f_src_requests_sessions_py_merge_hooks
f_src_requests_sessions_py_merge_environment_settings -->|вызывает| f_src_requests_sessions_py_merge_setting
f_src_requests_api_py_get -->|вызывает| f_src_requests_api_py_request
f_src_requests_api_py_options -->|вызывает| f_src_requests_api_py_request
f_src_requests_api_py_head -->|вызывает| f_src_requests_api_py_request
f_src_requests_api_py_post -->|вызывает| f_src_requests_api_py_request
f_src_requests_api_py_put -->|вызывает| f_src_requests_api_py_request
f_src_requests_api_py_patch -->|вызывает| f_src_requests_api_py_request
f_src_requests_api_py_delete -->|вызывает| f_src_requests_api_py_request
f_src_requests_utils_py_extract_zipped_paths -->|вызывает| f_src_requests_utils_py_atomic_open
f_src_requests_utils_py_parse_list_header -->|вызывает| f_src_requests_utils_py_unquote_header_value
f_src_requests_utils_py_parse_dict_header -->|вызывает| f_src_requests_utils_py_unquote_header_value
f_src_requests_utils_py_get_unicode_from_response -->|вызывает| f_src_requests_utils_py_get_encoding_from_headers
f_src_requests_utils_py_requote_uri -->|вызывает| f_src_requests_utils_py_unquote_unreserved
f_src_requests_utils_py_address_in_network -->|вызывает| f_src_requests_utils_py_dotted_netmask
f_src_requests_utils_py_should_bypass_proxies -->|вызывает| f_src_requests_utils_py_is_ipv4_address
f_src_requests_utils_py_should_bypass_proxies -->|вызывает| f_src_requests_utils_py_is_valid_cidr
f_src_requests_utils_py_should_bypass_proxies -->|вызывает| f_src_requests_utils_py_address_in_network
f_src_requests_utils_py_should_bypass_proxies -->|вызывает| f_src_requests_utils_py_set_environ
f_src_requests_utils_py_get_environ_proxies -->|вызывает| f_src_requests_utils_py_should_bypass_proxies
f_src_requests_utils_py_resolve_proxies -->|вызывает| f_src_requests_utils_py_should_bypass_proxies
f_src_requests_utils_py_resolve_proxies -->|вызывает| f_src_requests_utils_py_get_environ_proxies
f_src_requests_utils_py_default_headers -->|вызывает| f_src_requests_utils_py_default_user_agent
f_src_requests_help_py_main -->|вызывает| f_src_requests_help_py_info
f_src_requests_cookies_py_create_cookie -->|вызывает| f_src_requests_cookies_py_set
f_src_requests_cookies_py_morsel_to_cookie -->|вызывает| f_src_requests_cookies_py_create_cookie
f_src_requests_cookies_py_cookiejar_from_dict -->|вызывает| f_src_requests_cookies_py_create_cookie
f_src_requests_cookies_py_merge_cookies -->|вызывает| f_src_requests_cookies_py_cookiejar_from_dict
f_src_requests_cookies_py_set -->|вызывает| f_src_requests_cookies_py_remove_cookie_by_name
f_src_requests_cookies_py_set -->|вызывает| f_src_requests_cookies_py_morsel_to_cookie
f_src_requests_cookies_py_set -->|вызывает| f_src_requests_cookies_py_create_cookie
f_src_requests_cookies_py___delitem__ -->|вызывает| f_src_requests_cookies_py_remove_cookie_by_name
